# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# ----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3
clone:
  depth: full
pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - node
        script:
          - npm install
  branches:
    staging:
      - step:
          name: Build and Test
          caches:
            - node
          script:
            - apt-get update && apt-get install --yes zip
            - npm install
            - zip -r application-$BITBUCKET_BUILD_NUMBER.zip . Dockerfile Dockerrun.aws.json
          artifacts: 
            - application-*.zip
      - step:
          name: Deploy to staging
          deployment: staging
          script:
            - pipe: atlassian/aws-elasticbeanstalk-deploy:0.5.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                APPLICATION_NAME: 'code-crow'
                ENVIRONMENT_NAME: 'staging'
                ZIP_FILE: 'application-$BITBUCKET_BUILD_NUMBER.zip'
                S3_BUCKET: $AWS_S3_BUCKET
                WAIT: 'true'
                DEBUG: 'true'

    master:
      - step:
          name: Build and Test
          caches:
            - node
          script:
            - npm install
      - step:
          name: Deploy to production
          deployment: production
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
