FROM ubuntu:18.04
WORKDIR '/app'
COPY . .
RUN apt-get update \
    && apt-get -y install curl
RUN curl -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh
RUN bash nodesource_setup.sh
RUN apt install nodejs -y
RUN apt-get -y install make g++ python3 
RUN npm install -g @angular/cli \
    && npm install 
EXPOSE 4040
ARG NODE_ENV_
ARG SERVER_PORT_
ARG JWT_SECRET_
ARG MONGO_HOST_
ARG MEAN_FRONTEND_
ARG MONGO_URI_
ARG GITHUB_CLIENT_ID_
ARG GITHUB_CLIENT_SECRET_
ARG GITHUB_CALLBACK_URL_
ARG BITBUCKET_CLIENT_ID_
ARG BITBUCKET_CLIENT_SECRET_
ARG BITBUCKET_CALLBACK_URL_
ARG GITLAB_CLIENT_ID_
ARG GITLAB_CLIENT_SECRET_
ARG GITLAB_CALLBACK_URL_
ARG TWILIO_CHAT_SERVICE_SID_
ARG TWILIO_ACCOUNT_SID_
ARG TWILIO_API_KEY_
ARG TWILIO_API_SECRET_
ARG EMAIL_ADDRESS_
ARG EMAIL_PASSWORD_
ARG CODE_CROW_EMAIL_
ARG STRIPE_PK_
ARG STRIPE_SK_
ARG S3_BUCKET_VIDEOS_
ARG S3_BUCKET_NEWS_
ARG S3_BUCKET_LEGAL_DOCS_
ARG S3_BUCKET_ATTACHMENTS_
ARG AWS_ACCESS_KEY_
ARG AWS_ACCESS_SECRET_
ARG FFMPEG_PATH_
ENV NODE_ENV=$NODE_ENV_
ENV SERVER_PORT=$SERVER_PORT_
ENV JWT_SECRET=$JWT_SECRET_
ENV MONGO_HOST=$MONGO_HOST_
ENV MEAN_FRONTEND=$MEAN_FRONTEND_
ENV MONGO_URI=$MONGO_URI_
ENV GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID_
ENV GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET_
ENV GITHUB_CALLBACK_URL=$GITHUB_CALLBACK_URL_
ENV BITBUCKET_CLIENT_ID=$BITBUCKET_CLIENT_ID_
ENV BITBUCKET_CLIENT_SECRET=$BITBUCKET_CLIENT_SECRET_
ENV BITBUCKET_CALLBACK_URL=$BITBUCKET_CALLBACK_URL_
ENV GITLAB_CLIENT_ID=$GITLAB_CLIENT_ID_
ENV GITLAB_CLIENT_SECRET=$GITLAB_CLIENT_SECRET_
ENV GITLAB_CALLBACK_URL=$GITLAB_CALLBACK_URL_
ENV TWILIO_CHAT_SERVICE_SID=$TWILIO_CHAT_SERVICE_SID_
ENV TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID_
ENV TWILIO_API_KEY=$TWILIO_API_KEY_
ENV TWILIO_API_SECRET=$TWILIO_API_SECRET_
ENV EMAIL_ADDRESS=$EMAIL_ADDRESS_
ENV EMAIL_PASSWORD=$EMAIL_PASSWORD_
ENV CODE_CROW_EMAIL=$CODE_CROW_EMAIL_
ENV STRIPE_PK=$STRIPE_PK_
ENV STRIPE_SK=$STRIPE_SK_
ENV S3_BUCKET_VIDEOS=$S3_BUCKET_VIDEOS_
ENV S3_BUCKET_NEWS=$S3_BUCKET_NEWS_
ENV S3_BUCKET_LEGAL_DOCS=$S3_BUCKET_LEGAL_DOCS_
ENV S3_BUCKET_ATTACHMENTS=$S3_BUCKET_ATTACHMENTS_
ENV AWS_ACCESS_KEY=$AWS_ACCESS_KEY_
ENV AWS_ACCESS_SECRET=$AWS_ACCESS_SECRET_
ENV FFMPEG_PATH=$FFMPEG_PATH_
CMD [ "npm", "run", "start" ]
